### ISSUE TITLE
Align with new WebIDL constructor syntax

### ISSUE THREAD

**Issue by pmdartus** [jsdom/webidl2js#131]
Recently, the WebIDL spec replaced the `[Constructor]` extended attribute by a `constructor` operation ([WebIDL spec PR](https://github.com/heycam/webidl/pull/700)). We are currently in the process of updating all the depending specification to use this new syntax ([HTML spec PR](https://github.com/whatwg/html/pull/4915), [DOM spec PR](https://github.com/whatwg/dom/pull/786/files)).

**Comment by ExE-Boss** [comment]
I&nbsp;didn’t&nbsp;realise that&nbsp;**WebIDL2JS** still&nbsp;uses the&nbsp;legacy&nbsp;`[Constructor]` extended&nbsp;attribute while&nbsp;working&nbsp;on&nbsp;<https://github.com/jsdom/jsdom/pull/2737>.
