### ISSUE TITLE
The `any` and `object` types don't generate `utils.tryWrapperForImpl(…)` or `utils.tryImplForWrapper(…)`

### ISSUE THREAD

**Issue by ExE-Boss** [jsdom/webidl2js#149]
This&nbsp;has caused&nbsp;several WPT&nbsp;failures during&nbsp;the&nbsp;development of&nbsp;<https://github.com/jsdom/jsdom/pull/2737>.

Arguably, `object`&nbsp;should&nbsp;require `utils.tryWrapperForImpl` and&nbsp;`utils.tryImplForWrapper` &nbsp;as&nbsp;well.

**Comment by TimothyGu** [comment]
See #152 on why I don't think this is a good idea.
