### ISSUE TITLE
Pass global object to static methods

### ISSUE THREAD

**Issue by TimothyGu** [jsdom/webidl2js#186]
This is needed for things like `DOMRect`'s [`fromRect()`](https://drafts.fxtf.org/geometry/#dom-domrect-fromrect).

**Comment by domenic** [comment]
Continuing the conversation from #211: I think I like Chromium's mechanism, where by default you don't get the global object passed, but you can opt in with an extended attribute. I'm thinking `[WebIDL2JSCallWithGlobal]` which makes the first arugment always be the global object.

What do you think?

**Comment by TimothyGu** [comment]
That works.
