### ISSUE TITLE
Faster /lib/output/utils.js

### ISSUE THREAD

**Issue by lehni** [jsdom/webidl2js#19]
Wouldn't this version make more sense, as it would avoid the repeated lookups on the `module.exports.*` object chain in all these methods that are called behind the scenes all the time?

```js
"use strict";

function mixin(target, source) {
  const keys = Object.getOwnPropertyNames(source);
  for (let i = 0; i < keys.length; ++i) {
    if (keys[i] in target) {
      continue;
    }

    Object.defineProperty(target, keys[i], Object.getOwnPropertyDescriptor(source, keys[i]));
  }
};

const wrapperSymbol = Symbol("wrapper");
const implSymbol = Symbol("impl");

function wrapperForImpl(impl) {
  return impl ? impl[wrapperSymbol] : null;
};

function implForWrapper(wrapper) {
  return wrapper ? wrapper[implSymbol] : null;
};

function tryWrapperForImpl(impl) {
  const wrapper = wrapperForImpl(impl);
  return wrapper ? wrapper : impl;
};

function tryImplForWrapper(wrapper) {
  const impl = implForWrapper(wrapper);
  return impl ? impl : wrapper;
};

module.exports.mixin = mixin;
module.exports.wrapperSymbol = wrapperSymbol;
module.exports.implSymbol = implSymbol;
module.exports.wrapperForImpl = wrapperForImpl;
module.exports.implForWrapper = implForWrapper;
module.exports.tryWrapperForImpl = tryWrapperForImpl;
module.exports.tryImplForWrapper = tryImplForWrapper;
```

**Comment by domenic** [comment]
I doubt it. Most modern implementations do not actually do a property lookup each time; they have caches. If you can produce benchmarks showing a real improvement then maybe.

**Comment by lehni** [comment]
I agree with this observation in general, but there are a few reasons why I would treat this situation differently:
- These methods are used so heavily everywhere to bridge wrappers and implementations, e.g. on each value passed to a setter, ore returned from a getter.
- Each call involves two lookups each time with potential cache misses.
- The code that wouldn't require the JS engine to be smart about it isn't actually longer, or more complex.

So I wondered why not write it this way to be safe...

**Comment by domenic** [comment]
Because we have faith in JS VMs until benchmarks show otherwise.

**Comment by lehni** [comment]
Fair enough : )

**Comment by lehni** [comment]
I just did a little test, and it does make a difference, but not a massive one. Still worth this gentle optimization in my opinion:

The code:

```js
var canvas = document.createElement('canvas');
var count = 100000000;
console.time('implForWrapper');
for (var i = 0; i < count; i++) {
    idlUtils.implForWrapper(canvas);
}
console.timeEnd('implForWrapper');
```

With the current code, executed 3 times:

implForWrapper: 2013ms
implForWrapper: 2097ms
implForWrapper: 2020ms

With my proposed change, everything else the same:

implForWrapper: 1847ms
implForWrapper: 1973ms
implForWrapper: 1843ms
