### ISSUE TITLE
Separating constructor and new?

### ISSUE THREAD

**Issue by domenic** [jsdom/webidl2js#193]
I'm trying to implement https://github.com/whatwg/streams/pull/1035 and running into the issue that we don't have a way to invoke the Web IDL [new](https://heycam.github.io/webidl/#new) operation without also invoking the impl constructor.

The impl constructor is what backs the wrapper constructor. But in specs we have two different paths for creating platform objects:

- `new PlatformObject()` from JS code runs [these steps](https://heycam.github.io/webidl/#create-an-interface-object)
- Specs will do "[new](https://heycam.github.io/webidl/#new) `PlatformObject`" and then initialize them directly.

We don't currently have a way of doing the latter.

I'll probably investigate with some patches locally in the streams repo, but this issue can track upstreaming them.

**Comment by domenic** [comment]
This is what I came up with. It does not require any impl-side changes.

```js
exports.webidlNew = (globalObject, typeName, implModule) => {
  if (globalObject[utils.ctorRegistrySymbol] === undefined) {
    throw new Error('Internal error: invalid global object');
  }

  const ctor = globalObject[utils.ctorRegistrySymbol][typeName];
  if (ctor === undefined) {
    throw new Error(`Internal error: constructor ${typeName} is not installed on the passed global object`);
  }

  const obj = Object.create(ctor.prototype);
  Object.defineProperty(obj, utils.implSymbol, {
    value: Object.create(implModule.implementation.prototype),
    configurable: true
  });
  obj[utils.implSymbol][utils.wrapperSymbol] = obj;
  return obj[utils.implSymbol];
};
```

The arguments would change (to just globalObject, I think) if we exported this from the generated file. And we'd want to do some work to deduplicate the contents of this function with create/createImpl/setup. But it seems to work.

Naming it `new` is probably reasonable if it's an export, so that you'd use it as `MyClass.new(globalObject)`. I named mine `webidlNew` because it's just in a utils file, and I wanted to be able to do `const { webidlNew } = require("./utils.js")`.

**Comment by TimothyGu** [comment]
How do you call the impl constructor after creating an object with `webidlNew`? Just wondering how this is useful.

**Comment by domenic** [comment]
You don't; you fill in the slots manually. See for example https://whatpr.org/streams/1035.html#acquire-readable-stream-byob-reader vs. https://whatpr.org/streams/1035.html#default-reader-constructor .
