### ISSUE TITLE
Impl needs to be able to expose utility methods

### ISSUE THREAD

**Issue by Sebmaster** [jsdom/webidl2js#2]
They should be proxied so some property in the wrapper class.

**Comment by domenic** [comment]
For example, in jsdom's current situation, `window` does:

```js
idlUtils.implForWrapper(this, "EventTarget")._events = Object.create(null);
```

It should be able to do something like

```js
EventTarget.clearEvents(this);
```

and then EventTarget-impl.js defines something like

```js
exports.utils = {
  clearEvents(wrapper) {
    implForWrapper(wrapper, "EventTarget")._events = Object.create(null);
  }
};
```

and then the code generator proxies the method in EventTarget-impl.js to one in EventTarget.js.

**Comment by TimothyGu** [comment]
An alternative I prefer is `implForWrapper(this)._clearEvents`, which plays better with my recent change of eliminating build-time require() of the implementation file. This works with `implements` mixins too if we apply the same mixin algorithm to the impl classes.

**Comment by domenic** [comment]
If it helps with eliminating the circular dependencies then I'm happy to go with a slightly-more-awkward approach. Feel free to close.

**Comment by TimothyGu** [comment]
In most cases it's actually more convenient to write `this._doSomething(arg)` than `Class.doSomething(this, arg)`. The `implForWrapper` I wrote in my last comment is only needed for Window objects, which are weird hybrids.

Let's close this then.
