### ISSUE TITLE
Support [PutForwards=value]

### ISSUE THREAD

**Issue by domenic** [jsdom/webidl2js#20]
It's now on classList, causing some WPT to fail in jsdom after updating them.

**Comment by Sebmaster** [comment]
Tried implementing in c3a101006d9028b7253eafaad19f84a573d43e10 and it seems to generate the correct source, but might've missed an edge-case. Released as pre-minor 4.2.0-0.

**Comment by domenic** [comment]
Works, ship it :+1:

**Comment by Sebmaster** [comment]
Done
