### ISSUE TITLE
tryWrapperForImpl converts "" to undefined

### ISSUE THREAD

**Issue by domenic** [jsdom/webidl2js#22]
Maybe it shouldn't be applied to things whose return values are primitives, like DOMString or a numeric type?

Blocking a Navigator overhaul.

**Comment by Sebmaster** [comment]
You sure that's what's happening?

```js
> idlUtils = require('./lib/output/utils')
> idlUtils.tryImplForWrapper('') // ''
```

**Comment by domenic** [comment]
Wow, yeah, my bad; I read the code wrong. The real bug was that my method body was `"";` instead of `undefined;`. Would be nice if ESLint had caught that...

Will open a separate issue on perhaps omitting the conversion for primitives.
