### ISSUE TITLE
Consider removing auto-unwrapping for primitive return values

### ISSUE THREAD

**Issue by domenic** [jsdom/webidl2js#23]
DOMString, numeric types, promise types... anything that isn't an interface type, we could do `return this[impl].prop` instead of `return utils.tryWrapperForImpl(this[impl].prop)`. (Or for methods.)

This would be purely a perf optimization.

**Comment by Sebmaster** [comment]
Should be fixed, can you verify so I can push a release?

**Comment by domenic** [comment]
Installed webidl2js from git and jsdom test suite still passes. Output looks nice and simple. :+1: from me.
