### ISSUE TITLE
[WebIDL2JSValueAsUnsupported=undefined] doesn't work anymore

### ISSUE THREAD

**Issue by domenic** [jsdom/webidl2js#235]
Trying to upgrade jsdom to the latest webidl2js fails. This is likely due to webidl2.js updating to consider undefined as a token.

**Comment by TimothyGu** [comment]
Oh no. Does the `_undefined` trick work?

**Comment by domenic** [comment]
I think it does, although I now need to find a "before" version of the generated file to make sure... This might be an easy fix.

**Comment by domenic** [comment]
Yeah, so I guess this is easy; we should just fix the webidl2js docs.
