### ISSUE TITLE
Reformat the output somehow

### ISSUE THREAD

**Issue by domenic** [jsdom/webidl2js#35]
The indentation is already not perfect, and https://github.com/jsdom/webidl2js/pull/33 is going to add more imperfect indentation.

It would be ideal if while writing webidl2js, we could just ignore the indentation issues (or use whichever looks nicer inside the webidl2js source code), then have a postprocessing step that reformats everything for us. Maybe eslint's fix option, or maybe something simpler based on just esprima.

**Comment by TimothyGu** [comment]
A more radical approach is we can just rewrite the entire code generator based on Babel or escodegen -- that is, generating an AST instead of JS code directly. Something like [babel-template](https://www.npmjs.com/package/babel-template) makes it less painful than it would appear at first.

**Comment by Sebmaster** [comment]
Oh yes. babel-template looks awesome. I originally wanted to avoid building ASTs due to the verbosity, but this might just be perfect.

**Comment by domenic** [comment]
It's worth noting that the original [domenic/webidl-class-generator](https://github.com/domenic/webidl-class-generator) did something similar using Traceur's babel-template counterpart. See e.g. https://github.com/domenic/webidl-class-generator/blob/master/lib/code-generation.js

**Comment by domenic** [comment]
For direct source-to-source prettification, https://github.com/jlongster/prettier is the new hotness.

**Comment by domenic** [comment]
OK, so I did the prettier part of this. That was easy.

Remaining tasks until I personally am happy:

- [ ] Reformat all multiline code strings in the source to be indented in a way that is pleasing to read and write, instead of concerned with what the output would look like. (E.g., have leading whitespace indentation as if they were code and so on.)
- [ ] Add an eslint config to this project, probably similar to jsdom's, and fix all issues with this project.
- [ ] Change from prettier to [prettier-eslint](https://github.com/prettier/prettier-eslint) to get even more cleanups and fixups, using the project's ESLint config.

But I want to delay these until landing #33 as I don't want to make @TimothyGu rebase unnecessarily on any lint fixes and reformatting. So this is on hold for a little bit.

**Comment by TimothyGu** [comment]
> Change from prettier to prettier-eslint to get even more cleanups and fixups

I'm not sure if we want to put ESLint in webidl2js's `dependencies`, which is necessary for prettier-eslint to work. ESLint is much bigger than prettier, while prettier has 0 dependencies (since it's bundled by rollup).

**Comment by Sebmaster** [comment]
> I'm not sure if we want to put ESLint in webidl2js's `dependencies`, which is necessary for prettier-eslint to work.

Since webidl2js is mostly a `devDependencies` tool in general itself, I don't think size considerations matter much. It's not used at runtime anyways.

**Comment by domenic** [comment]
I guess this is indeed good enough as-is.
