### ISSUE TITLE
Generated file mixedInto array always seems empty?

### ISSUE THREAD

**Issue by domenic** [jsdom/webidl2js#53]
Browsing through several important mixins in jsdom, it always seems empty. Can we remove it?

**Comment by domenic** [comment]
I guess the intent was to make is/isImpl work, but they don't currently since it's always empty.

**Comment by TimothyGu** [comment]
It looks empty but the array is populated at runtime:

https://github.com/jsdom/webidl2js/blob/fb1698fca5354ccac4fb338c468ca68f1fb463e6/lib/constructs/interface.js#L361

**Comment by domenic** [comment]
Oh, interesting. I think we should add a comment to the output explaining this; we can use this issue to track that. In the meantime I'll fix the readme.
