### ISSUE TITLE
Don't export most things, for mixins

### ISSUE THREAD

**Issue by domenic** [jsdom/webidl2js#55]
See also #53. is/isImpl and maybe mixedInto make sense. But most of the rest of the exports don't.

To reliably identify a mixin, we can either wait for https://github.com/heycam/webidl/issues/363 or we can use a custom extended attribute in the meantime.

**Comment by TimothyGu** [comment]
Are there examples of interfaces defined with NoInterfaceObject but is not a mixin?

**Comment by domenic** [comment]
A few legacy ones. E.g. https://html.spec.whatwg.org/#external

**Comment by TimothyGu** [comment]
In that case, could we specifically flag the few NoInterfaceObject non-mixin interfaces and default to the mixin behavior for NoInterfaceObject? I could see the argument against this of course but just thought it might cause less churn.

**Comment by domenic** [comment]
I think I'd rather tag the mixins since we're going to eventually make mixins first class in Web IDL anyway so it'd be nice to get a sense of which ones they are.

**Comment by TimothyGu** [comment]
Sounds just fine to me.

**Comment by ExE-Boss** [comment]
Is this supposed to be closed?

Because README.md says that this is still an issue: https://github.com/jsdom/webidl2js/blob/9f103a29bd58a79f8ac7dcf7fe5cac43cd176ed0/README.md#L130

Also, #68’s description says that it doesn’t fix this.

**Comment by TimothyGu** [comment]
Ugh, GitHub's auto-closed this issue even though I said:

> Note, this does not yet fix #55

Thanks for the note @ExE-Boss!

**Comment by ExE-Boss** [comment]
Yeah, that’s because you wrote `“fix”` followed by the issue number separated by a single space (`U+0020`), [which is all GitHub cares about](https://help.github.com/en/articles/closing-issues-using-keywords).

**Comment by TimothyGu** [comment]
Fixed in #135. Interface mixins don’t cause files to be generated.
