### ISSUE TITLE
What is the expose format?

### ISSUE THREAD

**Issue by domenic** [jsdom/webidl2js#58]
That is, why is it

```js
expose: {
  Window: { Node: Node }
}
```

instead of 

```js
expose: ["Window"]
```

and then we know the thing to expose is the `interface` export, and then name to expose is `interface.name`?

**Comment by Sebmaster** [comment]
This is intended for stuff like `ImageHTMLElement`, which is also exposed as `Image`.

**Comment by domenic** [comment]
It's not though. window.HTMLImageElement !== window.Image. window.Image is a useful factory function, whereas window.HTMLImageElement throws.

**Comment by Sebmaster** [comment]
Right, I had hoped that this would be somehow possible, maybe my having an `expose` prop on the impl export which can add more stuff to the global?

**Comment by domenic** [comment]
Hmm, I see, that makes sense. So in the future we'll do something like

```js
expose: {
  Window: {
    HTMLImageElement: HTMLImageElement,
    Image: Image
  }
}
```

where `Image` is a generated wrapper that calls into something like `implModule.namedConstructor_Image` or similar.

**Comment by domenic** [comment]
Well, I'm not sure about the generated wrapper part (seems like a recipe for circular dependencies, since namedConstructor_Image would need to use one of the create functions from the generated wrapper). But the general idea makes sense. So let me close this and update #60.
