### ISSUE TITLE
Make too-few-arguments error message nicer

### ISSUE THREAD

**Issue by domenic** [jsdom/webidl2js#6]
1. "2 argument" should be "2 arguments"
2. Use template strings instead of ` + arguments.length + `.

Obviously only 1 is user-facing.

**Comment by Sebmaster** [comment]
Fixes 1 with eb3f56affc0e247b8e5d79e639861208e6f32c60. Not sure about 2, the necessary escaping makes it a bit ugly, so I think I'll hold off on this.
