### ISSUE TITLE
Do we really need [WebIDL2JSValueAsUnsupported], or would convention be enough?

### ISSUE THREAD

**Issue by domenic** [jsdom/webidl2js#61]
Continuing https://github.com/jsdom/webidl2js/pull/48#issuecomment-322092160. I am wondering whether it would be OK to just have the sentinel value always be undefined, and then no extended attribute would be needed?

**Comment by TimothyGu** [comment]
I wondered about that initially, but the point of the extended attribute is to avoid duplication of the logic in the implementation file. Take NodeList:

```webidl
interface NodeList {
  getter Node? item(unsigned long index);
  readonly attribute unsigned long length;
  iterable<Node>;
};
```

`item` is *spec'd* to return null if the item does not exist and is not supported. If we were to force `undefined` as "not supported" we would need to have a separate `undefined`-returning function. I don't want that.

I suppose it might be alright to make `null` the sentinel though, but I'm not entirely sure if the entire web platform doesn't have a named getter that returns `null` as a legitimate, supported property name. Plus, IMO we also need to provide an escape hatch for situations like the one written in the note before [Example 18](https://heycam.github.io/webidl/#example-bac9651d) in Web IDL, hence the creation of this extended attribute as an opt-in.

**Comment by domenic** [comment]
Understood and makes sense. I'll work on documenting this!
