### ISSUE TITLE
Brand checks not strict enough

### ISSUE THREAD

**Issue by domenic** [jsdom/webidl2js#62]
This is low priority unless someone can think of an amazing fix. I'm mostly just documenting it for posterity.

In jsdom, you can fool brand checks by doing things like

```js
const obj = Object.create(document.createElement("p"));
obj.align; // should throw
```

This is due to how we do our `is()` checks.

**Comment by TimothyGu** [comment]
We could do an `hasOwnProperty` check for the impl symbol, hopefully that won't bring *too* much of a slowdown. We could also check the impl symbol property descriptor ensuring that it is a data property, but that's probably going to be slower.
