### ISSUE TITLE
Branding check could be nicer

### ISSUE THREAD

**Issue by domenic** [jsdom/webidl2js#7]
I think `!this[impl] || !(this instanceof EventTarget)` could become simply `!this[impl]` (or, `!(impl in this)`). I can't think of when `this[impl]` will be truthy but `this instanceof EventTarget` would be false.

**Comment by Sebmaster** [comment]
Hrm, how would this interact with `Object.setPrototypeOf`? `this[impl]` would still be true in this case but instanceof wouldn't, right?

**Comment by domenic** [comment]
Yeah but I'm pretty sure the brand check _should_ pass in that case. It still has all the right internal stuff. E.g. this works in my console:

```js
const t = new Text();
t.__proto__ = {};
Text.prototype.appendData.call(t); // TypeError not enough arguments
Text.prototype.appendData.call(t, ""); // works
document.body.appendChild(t);
```
