### ISSUE TITLE
Work around Safari/webkit `new.target can't come after a prefix operator` issue

### ISSUE THREAD

**Issue by mikemaccana** [jsdom/webidl2js#78]
Safaru currently fails on prototypes created using webidl2js with 

> new.target can't come after a prefix operator

This is a silly error and entirely Safari's fault. Literally you're not allowed to (from `whatwg-url`:

    function URL(url) {
      if (!new.target) {
        throw new TypeError(

Because [the bang throws webkit](https://stackoverflow.com/questions/45578781/new-target-with-a-prefix-operator). [Webkit has now been fixed](https://bugs.webkit.org/show_bug.cgi?id=157970#c17), but the current Safari in macOS High Sierra and iOS 11.02 `13604.1.38.1.6` still has the error.

    if (new.target === undefined) {

works fine as a workaround. Ideally Apple would already have a new Safari rolled out, but in the meantime, and for older devices, can we get `webidl2js` to use the workaround?

**Comment by Sebmaster** [comment]
What a weird limitation. We can do that though. Would you prepare a PR?

**Comment by stevenvachon** [comment]
Is it really in the best interest of this library to care about spec-incompliant browsers? Use a transpiler.

**Comment by danyao** [comment]
This is fixed recently in WebKit (https://bugs.webkit.org/show_bug.cgi?id=157970). It may not ship in Safari for a while. It would be nice if the library can work around it for the time being (seeing how small the fix is...)

**Comment by darylteo** [comment]
I've had to modify whatwg-url locally to get our builds working for Safari. Any chance this could be pushed soon so that whatwg-url can be updated too? Would realy be appreciated. Thanks @Sebmaster

**Comment by AnthonyTwoBears** [comment]
I'm using fabric.js which depends on jsdom and hitting this error in safari.

Has the suggested `if (new.target === undefined)` been implemented or does this have to be done locally and individually by all users of the library?  Whilst safari is being 'spec-incomplient' I don't think this problem can be ignored, basically the library isn't usable without a hack.  Or i'm I missing something ?

Thanks

**Comment by domenic** [comment]
The library is intended for use in Node.js, so if you are using it elsewhere, you'll need to create solutions specific for your environment.

**Comment by AnthonyTwoBears** [comment]
Im using fabric.js in a meteor application.   Meteor is a node.js application  framework. The application runs fine in Chrome & Firefox & Edge but fails in safari with the new.target can't come after prefix error.

The error is generated by the safari browser against code in the events.js file which has the 
`if (!new.target) {} conditional.`

I take this to mean that a bug is safari is causing this valid code to fail. Safari is at fault. But safari has a few users on the internet.

To 'get around' this problem with safari the code needs to be changed. Either in the library so that everyone benefits or individually by everyone who uses the library, correct ?

thanks

**Comment by domenic** [comment]
Yep, if you're using jsdom outside a supported environment (which you are), then you probably need to change its code in all sorts of ways.

**Comment by AnthonyTwoBears** [comment]
I'm actually using fabric.js, which seems to be aimed at the browser(s) not just node.js apps - yikes!

**Comment by griv** [comment]
@AnthonyTwoBears did you find a solution for this? I'm using meteor and fabric as well. All my iPad apps are broken :/

**Comment by AnthonyTwoBears** [comment]
Hi griv,

Yes, just remove the jsdom from your project. As dominic said this is a only required for a node.js application as it is a dom emulator. for your application running in a real browser its not needed.

You can develop desktop apps that use node.js on the client, eg visual studio code is node.js based I think.
