### ISSUE TITLE
transformer.addSource(idl, impl) should interpret both paths as relative to the same base directory

### ISSUE THREAD

**Issue by danyao** [jsdom/webidl2js#80]
When using relative paths with `transformer.addSource(idl, impl)`, `idl` is interpreted relative to the base directory, where as `impl` is interpreted relative to the output directory of `transformer.generate`.

For example, if my Node.js looks like this:
```javascript
transformer.addSource("idl", "impl");  // [*]
transformer.generate("wrappers");
```
And I have the following directory structure:
```
./
  idl/
    foo.webidl
  impl/
    Foo-impl.js
  wrappers/
```
The generated file `./wrappers/Foo.js` will contain the following that can't be resolved:
```javascript
const Impl = require("./impls/Foo-impl.js");
```

Changing Node.js to the following works, but looks unintuitive:
```javascript
transformer.addSource("idl", "../impl");
```

**Comment by TimothyGu** [comment]
We can `path.resolve()` the paths before using them in `addSource()` and `generate()`. @danyao can you submit a PR to fix that?

**Comment by Sebmaster** [comment]
Breaking change btw, need to major for it.

**Comment by danyao** [comment]
Yep I'll take a stab.

**Comment by danyao** [comment]
How do I "major for it"?

**Comment by TimothyGu** [comment]
@danyao Bumping version is part of the process of making releases. We'll take care of it. (I think @Sebmaster said that as a reminder.)
