### ISSUE TITLE
Unused functions in utils.js: getReferenceToBytes() and getCopyToBytes()

### ISSUE THREAD

**Issue by danyao** [jsdom/webidl2js#82]
`getReferenceToBytes()` and `getCopyToBytes()` are exported by [utils.js](https://github.com/jsdom/webidl2js/blob/master/lib/output/utils.js) but they don't seem to be used anywhere in the repository. Because they use Node's Buffer implementation, it adds ~2000 lines when converting the generated JavaScript into a single static file using browserify.

Should they be removed?

**Comment by TimothyGu** [comment]
They are designed to be used by the impl classes, but are provided by webidl2js since they are defined by the Web IDL spec. I suppose we can either just remove them or convert them to use proper ECMAScript APIs (e.g. Uint8Array).

**Comment by domenic** [comment]
I think they should be in a separate package, although for now we should delete them since nothing in jsdom uses them.
