### ISSUE TITLE
Implement [HTMLConstructor] extended attribute

### ISSUE THREAD

**Issue by mraerino** [jsdom/webidl2js#87]
*Follow-up to #44*

**Spec: [[HTMLConstructor]](https://html.spec.whatwg.org/multipage/dom.html#htmlconstructor)**

For the sake of https://github.com/tmpvar/jsdom/issues/1030 i really want to make the `[HTMLConstructor]` extended attribute work.

Are there any plans to be able to implement extended attributes from `jsdom`? How would this work?

The way I see this, `[HTMLConstructor]` could behave just like `[Constructor]` with some specials implemented:

- Check: No `[Constructor]` or `[NoInterfaceObject]` attributes present
- Check: Needs to be inheriting from `HTMLElement`
- Passes `new.target` to the implementation constructor as `newTarget`

I would like to get this in here first, so when this is through we can start using `[HTMLConstructor` in jsdom.

I'm happy to implement, but would need some proper guidance on the best way.

**Comment by Sebmaster** [comment]
We don't usually check the correctness of input idls, so that's not really necessary.

Should just be able to save this in `privateData` and pass it to the impl constructor [here](https://github.com/jsdom/webidl2js/blob/e8604c070d8f69784e0d54399bf0ddf44ad800ed/lib/constructs/interface.js#L349).

**Comment by mraerino** [comment]
Closing in favor of implementation in #88
