### ISSUE TITLE
Generate toString() methods for now

### ISSUE THREAD

**Issue by domenic** [jsdom/webidl2js#9]
When toStringTag lands in V8, we will get proper toStrings. But for now, generating a toString() method that returns `[object InterfaceName]` seems like a good stop-gap, since jsdom is already adding a lot of those in an ad-hoc way.

**Comment by Sebmaster** [comment]
This is not actually that easy since it requires analysis of the whole inheritance / mixin chain in order to discover stringifiers. Not sure I can get that done for 2.x.

**Comment by domenic** [comment]
Just do a "good enough" version for now?

**Comment by Sebmaster** [comment]
Tried, even the simplest things fail, i.e. URL + URLUtils href stringifier.
