### ISSUE TITLE
Internet Explorer?

### ISSUE THREAD

**Issue by darylteo** [jsdom/webidl2js#90]
With the other Safari issue, I've noticed that `new.target` is extremely new, and is not supported by Internet Explorer (any versions).

Is this a strong indication that you're only intending to support Edge? Or is this not intended for client side use? Because if so, I guess I've been extremely misled and I've got very unhappy IE customers :( and now I will need to find a replacement for whatwg-url.

**Comment by domenic** [comment]
This is really only intended for Node or browsers with JavaScript as good as Node. A special exception was made for Safari as the fix was so simple, but only Node is supported.

**Comment by darylteo** [comment]
That makes the decision quite clear for me then. Thanks very much for clarifying! 

Regards,
Daryl

**Comment by ovirovkin** [comment]
@darylteo did you found any alternative solutions to simulate internet explorer render?
