### ISSUE TITLE
"prototype" property exists for operations

### ISSUE THREAD

**Issue by TimothyGu** [jsdom/webidl2js#97]
```js
> const { window } = new (require('jsdom').JSDOM)();
> typeof window.Document.prototype.querySelector.prototype
'object'
```

compared with in a browser:

```js
> typeof window.Document.prototype.querySelector.prototype
"undefined"
```

**Comment by domenic** [comment]
Hmm. This is the downside of our property-setting approach instead of method declarations, I guess. (Method declarations have the wrong enumerability out of the box though.)

**Comment by TimothyGu** [comment]
We can fix up the enumerability bit fairly easily afterwards:

```js
this.str += `
  Object.defineProperties(${this.name}.prototype, {
    ${[...this.operations, ...this.attributes].map(({ name }) => `
      ${name}: { enumerable: true }
    `).join(", ")}
  });
`;
this.str += `
  Object.defineProperties(${this.name}, {
    ${[...this.staticOperations, ...this.staticAttributes].map(({ name }) => `
      ${name}: { enumerable: true }
    `).join(", ")}
  });
`;
```

Using class syntax will also help with some other things we are not doing right at the moment, such as `.name` property of certain functions (symbol-named and keyword-named), and of all attribute getters/setters.
